import { makeHandlerRaw } from '@unisane/gateway';
import { signOut, signoutFactory } from '@unisane/auth';

/* AUTO-GENERATED by 'npm run routes:gen' — DO NOT EDIT */

export const runtime = 'nodejs';

export const POST = makeHandlerRaw<unknown>(
  ({ op: "auth.signOut", allowUnauthed: true }),
  async ({ req, params, body, ctx, requestId }) => {
    const result = await (signoutFactory({ req, ctx, ...(params ? { params: params as Record<string, unknown> } : {}), requestId } as Parameters<typeof signoutFactory>[0]));
    return result as Response;
  }
);