packages:
  # Apps
  - "apps/*"

  # Core infrastructure
  - "packages/foundation/*"

  # Adapters (pluggable implementations)
  - "packages/adapters/*"

  # Shared business modules
  - "packages/modules/*"

  # Premium modules
  - "packages/pro/*"

  # UI packages
  - "packages/ui/*"

  # Development tooling
  - "packages/tooling/*"

  # Platform-specific modules (future)
  - "packages/crm/*"
  - "packages/ecommerce/*"
  - "packages/helpdesk/*"
  - "packages/ai-platform/*"

  # Starter templates
  - "starters/*"
