import { NavCategory } from './types';

export const NAV_DATA: NavCategory[] = [
  {
    id: 'home',
    label: 'Home',
    icon: 'home',
    items: [] 
  },
  {
    id: 'getting-started',
    label: 'Get started',
    icon: 'rocket_launch',
    items: [
      { id: 'installation', label: 'Installation', isHeader: false },
      { id: 'usage', label: 'Usage', isHeader: false },
      { id: 'theming', label: 'Theming', isHeader: false },
    ]
  },
  {
    id: 'foundations',
    label: 'Foundations',
    icon: 'palette',
    items: [
      { id: 'colors', label: 'Colors', isHeader: false },
      { id: 'typography', label: 'Typography', isHeader: false },
      { id: 'icons', label: 'Icons', isHeader: false },
      { id: 'layout', label: 'Layout Primitives', isHeader: false },
    ]
  },
  {
    id: 'components',
    label: 'Components',
    icon: 'widgets', 
    items: [
      { id: 'components-overview', label: 'Overview', isHeader: false },
      { id: 'accordion', label: 'Accordion' },
      { id: 'alert', label: 'Alert' },
      { id: 'avatar', label: 'Avatar' },
      { id: 'badge', label: 'Badge' },
      { id: 'bottom-sheet', label: 'Bottom Sheet' },
      { id: 'breadcrumb', label: 'Breadcrumb' },
      { id: 'button', label: 'Button' },
      { id: 'card', label: 'Card' },
      { id: 'carousel', label: 'Carousel' },
      { id: 'checkbox', label: 'Checkbox' },
      { id: 'chip', label: 'Chip' },
      { id: 'combobox', label: 'Combobox' },
      { id: 'command', label: 'Command' },
      { id: 'container', label: 'Container' },
      { id: 'context-menu', label: 'Context Menu' },
      { id: 'data-grid', label: 'Data Grid' },
      { id: 'date-picker', label: 'Date Picker' },
      { id: 'dialog', label: 'Dialog' },
      { id: 'dropdown', label: 'Dropdown' },
      { id: 'empty-state', label: 'Empty State' },
      { id: 'fab', label: 'FAB' },
      { id: 'file-upload', label: 'File Upload' },
      { id: 'focus-trap', label: 'Focus Trap' },
      { id: 'icon-button', label: 'Icon Button' },
      { id: 'image', label: 'Image' },
      { id: 'list', label: 'List' },
      { id: 'menu', label: 'Menu' },
      { id: 'navigation-drawer', label: 'Navigation Drawer' },
      { id: 'navigation-rail', label: 'Navigation Rail' },
      { id: 'pagination', label: 'Pagination' },
      { id: 'pane', label: 'Pane' },
      { id: 'popover', label: 'Popover' },
      { id: 'portal', label: 'Portal' },
      { id: 'progress', label: 'Progress' },
      { id: 'radio', label: 'Radio' },
      { id: 'rating', label: 'Rating' },
      { id: 'resizable', label: 'Resizable' },
      { id: 'ripple', label: 'Ripple' },
      { id: 'scroll-area', label: 'Scroll Area' },
      { id: 'segmented-button', label: 'Segmented Button' },
      { id: 'sheet', label: 'Sheet' },
      { id: 'skeleton', label: 'Skeleton' },
      { id: 'slider', label: 'Slider' },
      { id: 'snackbar', label: 'Snackbar' },
      { id: 'stat', label: 'Stat' },
      { id: 'stepper', label: 'Stepper' },
      { id: 'switch', label: 'Switch' },
      { id: 'table', label: 'Table' },
      { id: 'tabs', label: 'Tabs' },
      { id: 'text-field', label: 'Text Field' },
      { id: 'timeline', label: 'Timeline' },
      { id: 'tooltip', label: 'Tooltip' },
      { id: 'top-app-bar', label: 'Top App Bar' },
    ]
  },
  {
    id: 'patterns',
    label: 'Patterns',
    icon: 'dashboard',
    items: [
      { id: 'list-detail', label: 'List-Detail' },
      { id: 'feed', label: 'Feed' },
      { id: 'supporting-pane', label: 'Supporting Pane' },
    ]
  }
];