/**
 * SDK generation utilities
 */

/**
 * Convert string to PascalCase
 */
export function pascalCase(s: string): string {
  return s
    .replace(/(^|[^a-zA-Z0-9]+)([a-zA-Z0-9])/g, (_, __, c) => String(c).toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '');
}

/**
 * Convert string to camelCase
 */
export function camelCase(s: string): string {
  const pascal = pascalCase(s);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/**
 * Extract param names from a path template
 */
export function extractParamNames(path: string): string[] {
  return Array.from(path.matchAll(/:([a-zA-Z0-9_]+)/g)).map((x) => x[1] as string);
}

/**
 * Check if a route is an admin route
 */
export function isAdminRoute(name: string, metaOp?: string): boolean {
  if (typeof metaOp === 'string' && metaOp.startsWith('admin.')) return true;
  return name.toLowerCase().startsWith('admin');
}

/**
 * Parse operation key into namespace, group, and name
 */
export function parseOpKey(opKey: string): {
  ns: 'admin' | 'tenant' | 'public' | 'me' | null;
  group: string;
  name: string;
} {
  const parts = opKey.split('.');
  if (parts.length >= 3) {
    const ns = parts[0] as 'admin' | 'tenant' | 'public' | 'me';
    const group = parts[1] as string;
    const name = parts.slice(2).join('.');
    if (['admin', 'tenant', 'public', 'me'].includes(ns)) {
      return { ns, group, name };
    }
  }
  return { ns: null, group: parts[0] ?? '', name: parts.slice(1).join('.') };
}

/**
 * Generate auto-gen header comment
 */
export function header(scriptName: string = 'sdk:gen'): string {
  return `/* AUTO-GENERATED by '${scriptName}' — DO NOT EDIT */
/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars */`;
}
