import { makeHandlerRaw } from '@unisane/gateway';
import { getCsrf, csrfFactory } from '@unisane/auth';

/* AUTO-GENERATED by 'npm run routes:gen' — DO NOT EDIT */

export const runtime = 'nodejs';

export const GET = makeHandlerRaw<unknown>(
  ({ op: "auth.csrf", allowUnauthed: true }),
  async ({ req, params, body, ctx, requestId }) => {const result = await (csrfFactory({ req, ctx, ...(params ? { params: params as Record<string, unknown> } : {}), requestId } as Parameters<typeof csrfFactory>[0]));
    return result as Response;
  }
);